/// District and villages data for Vientiane Capital (English transliteration)
final Map<String, List<String>> districtVillages = {
  'Xaysetha': [
    'Phonxay',
    'Fay',
    'Naxay',
    'Nongbon',
    'Phonxavat',
    'Nongsangto',
    'Phonkheng',
    'Thatluang Neua',
    'Thatluang Klang',
    'Thatluang Tai',
    'Sisangvone',
    'Hongkae',
    'Saphangmo',
    'Phontan Tai',
    'Phontan Neua',
    'Viengchaleun',
    'Phonphanao',
    'Chommanee Neua',
    'Chommanee Klang',
    'Chommanee Tai',
    'Nongniang',
    'Hongsoubane',
    'Phonxavan',
    'Nonxanga',
    'Nonxavang',
    'Vangxay',
    'Houakhoua',
    'Nonkho Neua',
    'Nonkho Tai',
    'Nonhouay',
  ],
  'Sisattanak': [
    'Phiavat',
    'Simeung',
    'Hatkhao',
    'Kaoyod',
    'Phapho',
    'Phaxay',
    'Nongjane',
    'Dongpalane Thong',
    'Dongpalane Tha',
    'Phonxavan Neua',
    'Phonsinouan',
    'Phonxavan Tai',
    'Thongphanthong',
    'Xaphanthong Neua',
    'Xaphanthong Tai',
    'Phonpapao',
    'Donkoy',
    'Donnokkhoum',
    'Sokpaluang',
    'Beungkhayong',
    'Vatnak',
    'Thongklang',
    'Thaphalansay',
    'Donpamai',
    'Phannman',
    'Vatsob',
    'Phoxay',
    'Souanmon',
    'Sangviay',
    'Haysoke',
  ],
  'Xaythany': [
    'Saynamngern',
    'Sivilay',
    'Khamhoung',
    'Phakhao',
    'Xangkhou',
    'Xaphangmuek',
    'Dongdok',
    'Tanmixay',
    'Nongphaya',
    'Nathom',
    'Nongviengkham',
    'Donnoun',
    'Xay',
    'Xaysavang',
    'Houaydanmeuang',
    'Viengkeo',
    'Nonxengchan',
    'Houaytoeuy',
    'Dontiu',
    'Danxang',
    'Nonxaat',
    'Nonbokaeo',
    'Na',
    'Thangone',
    'Thasavang',
    'Viengphoukham',
    'Kaengkhai',
    'Hay',
    'Veuankham',
    'Samxaat',
    'Phonngam',
    'Phonxay',
  ],
  'Sikhottabong': [
    'Sithaane Neua',
    'Nongdouang Neua',
    'Nongdouang Tai',
    'Nongdouang Thong',
    'Phonxavat Tai',
    'Nongbouathong Tai',
    'Nongbouathong Neua',
    'Phonkham',
    'Dongnaxok Neua',
    'Dongnaxok Tai',
    'Nakham',
    'Khountaa Thong',
    'Khountaa Tha',
    'Oubmoung',
    'Nongpanay',
    'Vatxay Noi Thong',
    'Vatxay Nyai Tha',
    'Vatxay Noi Tha',
    'Nongxanokham',
    'Pakthang',
    'Akad',
    'Meuangva Tha',
    'Meuangva Thong',
    'Sixay Tha',
    'Sixay Thong',
    'Nyapha',
    'Sibounheuang Thong',
    'Sibounheuang Tha',
    'Nahae',
  ],
  'Chanthabouly': [
    'Vatcane',
    'Mixay',
    'Xiengyeun',
    'Sisaket',
    'Hatsady Neua',
    'Hatsady Tai',
    'Sixavat',
    'Saylom',
    'Thongkhankham',
    'Haysoke',
    'Anou',
    'Sihome',
    'Khoualouang',
    'Hongkha',
    'Thongtoum',
    'Dongmuang',
    'Xidamdouane',
    'Sibounheuang',
    'Thongxangnang',
    'Xavang',
    'Dongpahlaep',
    'Phontongjommanee',
    'Phontongsavat',
    'Hongxaeng',
    'Hongkaikaeo',
    'Phonxavang',
    'Nongtha Tai',
    'Nongtha Neua',
    'Nongpeung',
    'Bonangua',
    'Houayhong',
    'Dondaeng',
  ],
};
