/// District and village data for Vientiane Capital
/// English keys are used as internal values (for API matching).
/// Lao names are used for display when language is set to Lao.

final Map<String, List<String>> districtVillages = {
  'Xaysetha': [
    'Phonxay', 'Fay', 'Naxay', 'Nongbon', 'Phonxavat',
    'Nongsangto', 'Phonkheng', 'Thatluang Neua', 'Thatluang Klang',
    'Thatluang Tai', 'Sisangvone', 'Hongkae', 'Saphangmo',
    'Phontan Tai', 'Phontan Neua', 'Viengchaleun', 'Phonphanao',
    'Chommanee Neua', 'Chommanee Klang', 'Chommanee Tai',
    'Nongniang', 'Hongsoubane', 'Phonxavan', 'Nonxanga',
    'Nonxavang', 'Vangxay', 'Houakhoua', 'Nonkho Neua',
    'Nonkho Tai', 'Nonhouay',
  ],
  'Sisattanak': [
    'Phiavat', 'Simeung', 'Hatkhao', 'Kaoyod', 'Phapho',
    'Phaxay', 'Nongjane', 'Dongpalane Thong', 'Dongpalane Tha',
    'Phonxavan Neua', 'Phonsinouan', 'Phonxavan Tai',
    'Thongphanthong', 'Xaphanthong Neua', 'Xaphanthong Tai',
    'Phonpapao', 'Donkoy', 'Donnokkhoum', 'Sokpaluang',
    'Beungkhayong', 'Vatnak', 'Thongklang', 'Thaphalansay',
    'Donpamai', 'Phannman', 'Vatsob', 'Phoxay', 'Souanmon',
    'Sangviay', 'Haysoke',
  ],
  'Xaythany': [
    'Saynamngern', 'Sivilay', 'Khamhoung', 'Phakhao', 'Xangkhou',
    'Xaphangmuek', 'Dongdok', 'Tanmixay', 'Nongphaya', 'Nathom',
    'Nongviengkham', 'Donnoun', 'Xay', 'Xaysavang',
    'Houaydanmeuang', 'Viengkeo', 'Nonxengchan', 'Houaytoeuy',
    'Dontiu', 'Danxang', 'Nonxaat', 'Nonbokaeo', 'Na', 'Thangone',
    'Thasavang', 'Viengphoukham', 'Kaengkhai', 'Hay', 'Veuankham',
    'Samxaat', 'Phonngam', 'Phonxay',
  ],
  'Sikhottabong': [
    'Sithaane Neua', 'Nongdouang Neua', 'Nongdouang Tai',
    'Nongdouang Thong', 'Phonxavat Tai', 'Nongbouathong Tai',
    'Nongbouathong Neua', 'Phonkham', 'Dongnaxok Neua',
    'Dongnaxok Tai', 'Nakham', 'Khountaa Thong', 'Khountaa Tha',
    'Oubmoung', 'Nongpanay', 'Vatxay Noi Thong', 'Vatxay Nyai Tha',
    'Vatxay Noi Tha', 'Nongxanokham', 'Pakthang', 'Akad',
    'Meuangva Tha', 'Meuangva Thong', 'Sixay Tha', 'Sixay Thong',
    'Nyapha', 'Sibounheuang Thong', 'Sibounheuang Tha', 'Nahae',
  ],
  'Chanthabouly': [
    'Vatcane', 'Mixay', 'Xiengyeun', 'Sisaket', 'Hatsady Neua',
    'Hatsady Tai', 'Sixavat', 'Saylom', 'Thongkhankham', 'Haysoke',
    'Anou', 'Sihome', 'Khoualouang', 'Hongkha', 'Thongtoum',
    'Dongmuang', 'Xidamdouane', 'Sibounheuang', 'Thongxangnang',
    'Xavang', 'Dongpahlaep', 'Phontongjommanee', 'Phontongsavat',
    'Hongxaeng', 'Hongkaikaeo', 'Phonxavang', 'Nongtha Tai',
    'Nongtha Neua', 'Nongpeung', 'Bonangua', 'Houayhong', 'Dondaeng',
  ],
};

/// Lao names for districts
const Map<String, String> districtNamesLao = {
  'Xaysetha':    'ໄຊເສດຖາ',
  'Sisattanak':  'ສີສັດຕະນາກ',
  'Xaythany':    'ໄຊທານີ',
  'Sikhottabong':'ສີໂຄດຕະບອງ',
  'Chanthabouly':'ຈັນທະບູລີ',
};

/// Lao names for villages (keyed by English name)
const Map<String, String> villageNamesLao = {
  // Xaysetha
  'Phonxay':           'ໂພນໄຊ',
  'Fay':               'ຝາຍ',
  'Naxay':             'ນາໄຊ',
  'Nongbon':           'ໜອງບອນ',
  'Phonxavat':         'ໂພນຊະວາດ',
  'Nongsangto':        'ໜອງສ້າງຕໍ',
  'Phonkheng':         'ໂພນແຂງ',
  'Thatluang Neua':    'ທາດຫຼວງເໜືອ',
  'Thatluang Klang':   'ທາດຫຼວງກາງ',
  'Thatluang Tai':     'ທາດຫຼວງໃຕ້',
  'Sisangvone':        'ສີສ່ວງວົງ',
  'Hongkae':           'ຫ້ອງແກ',
  'Saphangmo':         'ສາພັງໝໍ',
  'Phontan Tai':       'ໂພນຕານໃຕ້',
  'Phontan Neua':      'ໂພນຕານເໜືອ',
  'Viengchaleun':      'ວຽງຈະເລີນ',
  'Phonphanao':        'ໂພນໂພ',
  'Chommanee Neua':    'ຈອມມະນີເໜືອ',
  'Chommanee Klang':   'ຈອມມະນີກາງ',
  'Chommanee Tai':     'ຈອມມະນີໃຕ້',
  'Nongniang':         'ໜອງນ້ຽງ',
  'Hongsoubane':       'ຫ້ອງໂສ້ວພານ',
  'Phonxavan':         'ໂພນຊາວັນ',
  'Nonxanga':          'ໜອງຊ້ັງ',
  'Nonxavang':         'ໜອງຊ້ວງ',
  'Vangxay':           'ວັງໄຊ',
  'Houakhoua':         'ຫົວຂົວ',
  'Nonkho Neua':       'ໜອງໂຄເໜືອ',
  'Nonkho Tai':        'ໜອງໂຄໃຕ້',
  'Nonhouay':          'ໜອງຫ້ວຍ',
  // Sisattanak
  'Phiavat':           'ພຽວາດ',
  'Simeung':           'ສີເມືອງ',
  'Hatkhao':           'ຫາດຂາວ',
  'Kaoyod':            'ເກົ້າຍອດ',
  'Phapho':            'ຜາໂພ',
  'Phaxay':            'ຜາໄຊ',
  'Nongjane':          'ໜອງຈັນ',
  'Dongpalane Thong':  'ດົງປາລານທົ່ງ',
  'Dongpalane Tha':    'ດົງປາລານທ່າ',
  'Phonxavan Neua':    'ໂພນຊາວັນເໜືອ',
  'Phonsinouan':       'ໂພນສີນວນ',
  'Phonxavan Tai':     'ໂພນຊາວັນໃຕ້',
  'Thongphanthong':    'ທົ່ງພັນທົ່ງ',
  'Xaphanthong Neua':  'ສາພັນທົ່ງເໜືອ',
  'Xaphanthong Tai':   'ສາພັນທົ່ງໃຕ້',
  'Phonpapao':         'ໂພນປ່າເປົ້າ',
  'Donkoy':            'ດອນຄ້ອຍ',
  'Donnokkhoum':       'ດອນໜອກຄູ່',
  'Sokpaluang':        'ໂສກປ່າຫຼວງ',
  'Beungkhayong':      'ເບິ່ງຄາຍ',
  'Vatnak':            'ວັດນາກ',
  'Thongklang':        'ທົ່ງກາງ',
  'Thaphalansay':      'ທ່າຜາລານໄຊ',
  'Donpamai':          'ດອນປ່າໄມ້',
  'Phannman':          'ພັນມ່ວນ',
  'Vatsob':            'ວັດໂສບ',
  'Phoxay':            'ໂພໄຊ',
  'Souanmon':          'ສວນໝາກ',
  'Sangviay':          'ສ້ວຍ',
  'Haysoke':           'ໄຮໂສກ',
  // Xaythany
  'Saynamngern':       'ສາຍນ້ຳເງິນ',
  'Sivilay':           'ສີວິໄລ',
  'Khamhoung':         'ຄຳຫ້ອງ',
  'Phakhao':           'ຜາຂາວ',
  'Xangkhou':          'ຊ້າງຂວາ',
  'Xaphangmuek':       'ສາພັງໝວກ',
  'Dongdok':           'ດົງໂດກ',
  'Tanmixay':          'ຕ້ານມີໄຊ',
  'Nongphaya':         'ໜອງພະຍາ',
  'Nathom':            'ນາທົ່ມ',
  'Nongviengkham':     'ໜອງວຽງຄຳ',
  'Donnoun':           'ດອນນຸ່ນ',
  'Xay':               'ໄຊ',
  'Xaysavang':         'ໄຊສະຫວ່າງ',
  'Houaydanmeuang':    'ຫ້ວຍດ່ານເມືອງ',
  'Viengkeo':          'ວຽງແກ້ວ',
  'Nonxengchan':       'ໜອງແຊງຈັນ',
  'Houaytoeuy':        'ຫ້ວຍເຕີຍ',
  'Dontiu':            'ດອນຕີ້ວ',
  'Danxang':           'ດ່ານຊ້າງ',
  'Nonxaat':           'ໜອງຊາດ',
  'Nonbokaeo':         'ໜອງໂບ້ແກ້ວ',
  'Na':                'ນາ',
  'Thangone':          'ທ່ານກອນ',
  'Thasavang':         'ທ່າສະຫວ່າງ',
  'Viengphoukham':     'ວຽງພູຄຳ',
  'Kaengkhai':         'ແກ່ງໄຂ',
  'Hay':               'ໄຮ',
  'Veuankham':         'ເວີນຄຳ',
  'Samxaat':           'ສາມຊາດ',
  'Phonngam':          'ໂພນງາມ',
  // Sikhottabong
  'Sithaane Neua':     'ສີທ່ານເໜືອ',
  'Nongdouang Neua':   'ໜອງດ້ວງເໜືອ',
  'Nongdouang Tai':    'ໜອງດ້ວງໃຕ້',
  'Nongdouang Thong':  'ໜອງດ້ວງທົ່ງ',
  'Phonxavat Tai':     'ໂພນຊະວາດໃຕ້',
  'Nongbouathong Tai': 'ໜອງບົວທົ່ງໃຕ້',
  'Nongbouathong Neua':'ໜອງບົວທົ່ງເໜືອ',
  'Phonkham':          'ໂພນຄຳ',
  'Dongnaxok Neua':    'ດົງນາໂຊກເໜືອ',
  'Dongnaxok Tai':     'ດົງນາໂຊກໃຕ້',
  'Nakham':            'ນ້ຳຄຳ',
  'Khountaa Thong':    'ຄຸ້ນຕ່າທົ່ງ',
  'Khountaa Tha':      'ຄຸ້ນຕ່າທ່າ',
  'Oubmoung':          'ອຸ້ບໝ່ວງ',
  'Nongpanay':         'ໜອງປ່ານາຍ',
  'Vatxay Noi Thong':  'ວັດໄຊນ້ອຍທົ່ງ',
  'Vatxay Nyai Tha':   'ວັດໄຊໃຫ່ຍທ່າ',
  'Vatxay Noi Tha':    'ວັດໄຊນ້ອຍທ່າ',
  'Nongxanokham':      'ໜອງຊ້ານໍ້ຄຳ',
  'Pakthang':          'ປາກທ່າງ',
  'Akad':              'ອ່ຳກາດ',
  'Meuangva Tha':      'ເມືອງວ່າທ່າ',
  'Meuangva Thong':    'ເມືອງວ່າທົ່ງ',
  'Sixay Tha':         'ສີໄຊທ່າ',
  'Sixay Thong':       'ສີໄຊທົ່ງ',
  'Nyapha':            'ຍ້ໍຜ່າ',
  'Sibounheuang Thong':'ສີບຸນເຮືອງທົ່ງ',
  'Sibounheuang Tha':  'ສີບຸນເຮືອງທ່າ',
  'Nahae':             'ນ້ຳແຫ',
  // Chanthabouly
  'Vatcane':           'ວັດຈ້ານ',
  'Mixay':             'ມີໄຊ',
  'Xiengyeun':         'ຊຽງເຢືອນ',
  'Sisaket':           'ສີສະເກດ',
  'Hatsady Neua':      'ຫາດສາຍເໜືອ',
  'Hatsady Tai':       'ຫາດສາຍໃຕ້',
  'Sixavat':           'ສີຊະວາດ',
  'Saylom':            'ໄສລົມ',
  'Thongkhankham':     'ທົ່ງຂ່ວງຄຳ',
  'Anou':              'ອານຸ',
  'Sihome':            'ສີໂຮມ',
  'Khoualouang':       'ຂົວຫຼວງ',
  'Hongkha':           'ຫ້ອງຂ່າ',
  'Thongtoum':         'ທົ່ງຕູ້ມ',
  'Dongmuang':         'ດົງເມືອງ',
  'Xidamdouane':       'ສີດຳດວນ',
  'Sibounheuang':      'ສີບຸນເຮືອງ',
  'Thongxangnang':     'ທົ່ງຊ້າງນ່ວງ',
  'Xavang':            'ຊາວ່ງ',
  'Dongpahlaep':       'ດົງປ່ຳແຫຼວ',
  'Phontongjommanee':  'ໂພນທົ່ງຈອມມະນີ',
  'Phontongsavat':     'ໂພນທົ່ງສາວາດ',
  'Hongxaeng':         'ຫ້ອງແຊງ',
  'Hongkaikaeo':       'ຫ້ອງໄກ່ແກ້ວ',
  'Phonxavang':        'ໂພນຊາວ່ງ',
  'Nongtha Tai':       'ໜອງທ່າໃຕ້',
  'Nongtha Neua':      'ໜອງທ່າເໜືອ',
  'Nongpeung':         'ໜອງເປືອງ',
  'Bonangua':          'ໂບ້ນາງົວ',
  'Houayhong':         'ຫ້ວຍຫ້ອງ',
  'Dondaeng':          'ດອນແດງ',
};

/// Returns the display name of a district based on locale.
String getDistrictDisplay(String englishName, bool isLao) {
  if (!isLao) return englishName;
  return districtNamesLao[englishName] ?? englishName;
}

/// Returns the display name of a village based on locale.
String getVillageDisplay(String englishName, bool isLao) {
  if (!isLao) return englishName;
  return villageNamesLao[englishName] ?? englishName;
}
